#Pull base image
FROM python:3.11

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /code

# Install dependencies
COPY requirements.txt /code
RUN pip install -r requirements.txt

# Copy project
COPY . /code

# start the server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
