"""upload flora

Revision ID: 16a2f6b10cb2
Revises: aec14d025695
Create Date: 2023-11-23 13:53:07.905777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a2f6b10cb2'
down_revision = 'aec14d025695'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flora_relocation', sa.Column('relocation_position_altitude', sa.Integer(), nullable=False))
    op.alter_column('flora_relocation', 'relocation_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=False)
    op.create_index(op.f('ix_flora_relocation_relocation_position_altitude'), 'flora_relocation', ['relocation_position_altitude'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flora_relocation_relocation_position_altitude'), table_name='flora_relocation')
    op.alter_column('flora_relocation', 'relocation_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=True)
    op.drop_column('flora_relocation', 'relocation_position_altitude')
    # ### end Alembic commands ###
