"""corrigiendo nudablle url y atribute imagen species

Revision ID: 2508a83ad0e8
Revises: eda70868f57f
Create Date: 2023-07-31 14:37:36.636869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2508a83ad0e8'
down_revision = 'eda70868f57f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
