"""probando

Revision ID: 4046bec0b456
Revises: 9aea218c7bb6
Create Date: 2023-09-24 02:03:51.586162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4046bec0b456'
down_revision = '9aea218c7bb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
