"""Inclusion de Key en taxonomia

Revision ID: 4fc30e03c2c0
Revises: 4046bec0b456
Create Date: 2023-10-07 13:56:32.822654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc30e03c2c0'
down_revision = '4046bec0b456'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_', sa.Column('key_gbif', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'class_', ['key_gbif'])
    op.add_column('family', sa.Column('key_gbif', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'family', ['key_gbif'])
    op.add_column('genus', sa.Column('key_gbif', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'genus', ['key_gbif'])
    op.add_column('order', sa.Column('key_gbif', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'order', ['key_gbif'])
    op.add_column('species', sa.Column('key_gbif', sa.Integer(), nullable=True))
    op.add_column('species', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'species', ['key_gbif'])
    op.create_foreign_key(None, 'species', 'status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'species', type_='foreignkey')
    op.drop_constraint(None, 'species', type_='unique')
    op.drop_column('species', 'status_id')
    op.drop_column('species', 'key_gbif')
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_column('order', 'key_gbif')
    op.drop_constraint(None, 'genus', type_='unique')
    op.drop_column('genus', 'key_gbif')
    op.drop_constraint(None, 'family', type_='unique')
    op.drop_column('family', 'key_gbif')
    op.drop_constraint(None, 'class_', type_='unique')
    op.drop_column('class_', 'key_gbif')
    # ### end Alembic commands ###
