"""incluyendo check taxonomia en rescate de flora

Revision ID: 5930f8fb8dc1
Revises: 60fe106b92fb
Create Date: 2024-01-22 18:08:10.425893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5930f8fb8dc1'
down_revision = '60fe106b92fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
            'flora_rescue',
            sa.Column(
                'is_epiphyte_confirmed',
                sa.Boolean(),
                nullable=False,
                server_default='false'
                      ))
    op.add_column(
            'flora_rescue',
            sa.Column(
                'is_bryophyte_confirmed',
                sa.Boolean(),
                nullable=False,
                server_default='false'
                ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flora_rescue', 'is_bryophyte_confirmed')
    op.drop_column('flora_rescue', 'is_epiphyte_confirmed')
    # ### end Alembic commands ###
