"""Increase mark caracteres

Revision ID: 623754cd6421
Revises: a569b2c840aa
Create Date: 2024-10-02 13:38:28.038116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623754cd6421'
down_revision = 'a569b2c840aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('release_mammals', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('release_mammals', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('rescue_mammals', 'mark',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=350),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rescue_mammals', 'mark',
               existing_type=sa.String(length=350),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('release_mammals', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('release_mammals', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
