"""option nullable mark_id on rescue herpetofauna

Revision ID: 6663f8f9945a
Revises: e878fcaf8e6a
Create Date: 2023-10-29 03:16:12.270799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6663f8f9945a'
down_revision = 'e878fcaf8e6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rescue_herpetofauna', 'mark_herpetofauna_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rescue_herpetofauna', 'mark_herpetofauna_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
