"""number trancect herpetofauna unique

Revision ID: 6cb97f52e0f7
Revises: 78d06d01516d
Create Date: 2023-10-23 01:16:37.354425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb97f52e0f7'
down_revision = '78d06d01516d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'transect_herpetofauna', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transect_herpetofauna', type_='unique')
    # ### end Alembic commands ###
