"""arreglando rescue_mammals.mark

Revision ID: 728cbbf17720
Revises: c62c050c6f7d
Create Date: 2023-11-25 02:21:07.067133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728cbbf17720'
down_revision = 'c62c050c6f7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rescue_mammals_mark_key', 'rescue_mammals', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('rescue_mammals_mark_key', 'rescue_mammals', ['mark'])
    # ### end Alembic commands ###
