"""nombre_de_la_migracion

Revision ID: 87fb01258991
Revises: fe3ad653b39a
Create Date: 2023-10-16 01:02:59.401567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87fb01258991'
down_revision = 'fe3ad653b39a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rescue_herpetofauna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('specie_id', sa.Integer(), nullable=False),
    sa.Column('mark_herpetofauna_id', sa.Integer(), nullable=False),
    sa.Column('transect_herpetofauna_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mark_herpetofauna_id'], ['mark_herpetofauna.id'], ),
    sa.ForeignKeyConstraint(['specie_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['transect_herpetofauna_id'], ['transect_herpetofauna.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rescue_herpetofauna_id'), 'rescue_herpetofauna', ['id'], unique=False)
    op.add_column('mark_herpetofauna', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_constraint('mark_herpetofauna_species_id_fkey', 'mark_herpetofauna', type_='foreignkey')
    op.drop_constraint('mark_herpetofauna_tower_id_fkey', 'mark_herpetofauna', type_='foreignkey')
    op.drop_column('mark_herpetofauna', 'species_id')
    op.drop_column('mark_herpetofauna', 'tower_id')
    op.add_column('transect_herpetofauna', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transect_herpetofauna', 'created_at')
    op.add_column('mark_herpetofauna', sa.Column('tower_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('mark_herpetofauna', sa.Column('species_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('mark_herpetofauna_tower_id_fkey', 'mark_herpetofauna', 'towers', ['tower_id'], ['id'])
    op.create_foreign_key('mark_herpetofauna_species_id_fkey', 'mark_herpetofauna', 'species', ['species_id'], ['id'])
    op.drop_column('mark_herpetofauna', 'created_at')
    op.drop_index(op.f('ix_rescue_herpetofauna_id'), table_name='rescue_herpetofauna')
    op.drop_table('rescue_herpetofauna')
    # ### end Alembic commands ###
