"""fix observation max lenght mammals

Revision ID: 8b51b785e16c
Revises: 623754cd6421
Create Date: 2024-10-03 15:03:35.508958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b51b785e16c'
down_revision = '623754cd6421'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rescue_mammals', 'observation',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=350),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rescue_mammals', 'observation',
               existing_type=sa.String(length=350),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
