"""cambio de tablas mark herpetofauno y rescue

Revision ID: 96f587ee4c94
Revises: ebe89f6cceb8
Create Date: 2023-11-02 04:29:04.419441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f587ee4c94'
down_revision = 'ebe89f6cceb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mark_herpetofauna', sa.Column('rescue_herpetofauna_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'mark_herpetofauna', 'rescue_herpetofauna', ['rescue_herpetofauna_id'], ['id'])
    op.drop_constraint('rescue_herpetofauna_mark_herpetofauna_id_fkey', 'rescue_herpetofauna', type_='foreignkey')
    op.drop_column('rescue_herpetofauna', 'mark_herpetofauna_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rescue_herpetofauna', sa.Column('mark_herpetofauna_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('rescue_herpetofauna_mark_herpetofauna_id_fkey', 'rescue_herpetofauna', 'mark_herpetofauna', ['mark_herpetofauna_id'], ['id'])
    op.drop_constraint(None, 'mark_herpetofauna', type_='foreignkey')
    op.drop_column('mark_herpetofauna', 'rescue_herpetofauna_id')
    # ### end Alembic commands ###
