"""probando TMESTAMP

Revision ID: 976fb72b85fc
Revises: b5b146e119ca
Create Date: 2023-10-17 16:05:48.671517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976fb72b85fc'
down_revision = 'b5b146e119ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
