"""implementando check de specie en rescate de flora

Revision ID: 9de1832e99a4
Revises: 5930f8fb8dc1
Create Date: 2024-01-25 19:38:37.850035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de1832e99a4'
down_revision = '5930f8fb8dc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flora_relocation', sa.Column(
        'is_bryophyte_confirmed',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
        ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flora_relocation', 'is_bryophyte_confirmed')
    # ### end Alembic commands ###
