"""Status abbreviature

Revision ID: a569b2c840aa
Revises: 9de1832e99a4
Create Date: 2024-02-20 19:29:13.526376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a569b2c840aa'
down_revision = '9de1832e99a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('abbreviation', sa.String(), nullable=False))
    op.create_index(op.f('ix_status_abbreviation'), 'status', ['abbreviation'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_abbreviation'), table_name='status')
    op.drop_column('status', 'abbreviation')
    # ### end Alembic commands ###
