"""mejorando tabla de herpetofaina

Revision ID: ab7e3b67efa3
Revises: 87fb01258991
Create Date: 2023-10-16 01:24:14.316593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7e3b67efa3'
down_revision = '87fb01258991'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
