"""agregando genus and family to forofito

Revision ID: b0b9a6f1d8c3
Revises: 2508a83ad0e8
Create Date: 2023-07-31 18:02:05.305160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b9a6f1d8c3'
down_revision = '2508a83ad0e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flora_rescue', sa.Column('genus_bryophyte_id', sa.Integer(), nullable=True))
    op.add_column('flora_rescue', sa.Column('family_bryophyte_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'flora_rescue', 'genus', ['genus_bryophyte_id'], ['id'])
    op.create_foreign_key(None, 'flora_rescue', 'family', ['family_bryophyte_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flora_rescue', type_='foreignkey')
    op.drop_constraint(None, 'flora_rescue', type_='foreignkey')
    op.drop_column('flora_rescue', 'family_bryophyte_id')
    op.drop_column('flora_rescue', 'genus_bryophyte_id')
    # ### end Alembic commands ###
