"""include ephitet_name for specie and full_name for genus

Revision ID: b53563f05f17
Revises: fd7322f2ef88
Create Date: 2023-07-31 02:20:52.112421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53563f05f17'
down_revision = 'fd7322f2ef88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genus', sa.Column('genus_full_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_genus_genus_full_name'), 'genus', ['genus_full_name'], unique=True)
    op.add_column('species', sa.Column('specific_epithet', sa.String(), nullable=True))
    op.drop_index('ix_species_common_name', table_name='species')
    op.create_index(op.f('ix_species_specific_epithet'), 'species', ['specific_epithet'], unique=False)
    op.drop_column('species', 'common_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('common_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_species_specific_epithet'), table_name='species')
    op.create_index('ix_species_common_name', 'species', ['common_name'], unique=False)
    op.drop_column('species', 'specific_epithet')
    op.drop_index(op.f('ix_genus_genus_full_name'), table_name='genus')
    op.drop_column('genus', 'genus_full_name')
    # ### end Alembic commands ###
