"""Implementando fecha con zona horaria en rescue herpetofauna

Revision ID: b5b146e119ca
Revises: c04abdd052b2
Create Date: 2023-10-17 15:00:46.412913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b146e119ca'
down_revision = 'c04abdd052b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
