"""incluyendo genero y familia de forofito en relocalizacion

Revision ID: ba53565ed7eb
Revises: c4b99153fa40
Create Date: 2023-08-05 01:56:55.720914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba53565ed7eb'
down_revision = 'c4b99153fa40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flora_relocation', sa.Column('genus_bryophyte_id', sa.Integer(), nullable=True))
    op.add_column('flora_relocation', sa.Column('family_bryophyte_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'flora_relocation', 'genus', ['genus_bryophyte_id'], ['id'])
    op.create_foreign_key(None, 'flora_relocation', 'family', ['family_bryophyte_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flora_relocation', type_='foreignkey')
    op.drop_constraint(None, 'flora_relocation', type_='foreignkey')
    op.drop_column('flora_relocation', 'family_bryophyte_id')
    op.drop_column('flora_relocation', 'genus_bryophyte_id')
    # ### end Alembic commands ###
