"""Implementando fecha con zona horaria en rescue herpetofauna

Revision ID: c04abdd052b2
Revises: ab7e3b67efa3
Create Date: 2023-10-17 14:50:36.608800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04abdd052b2'
down_revision = 'ab7e3b67efa3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
