"""eliminando posicion de forofito

Revision ID: c4b99153fa40
Revises: 5020f89e91de
Create Date: 2023-08-04 21:10:51.340989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b99153fa40'
down_revision = '5020f89e91de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flora_relocation_bryophyte_position', table_name='flora_relocation')
    op.drop_column('flora_relocation', 'bryophyte_position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flora_relocation', sa.Column('bryophyte_position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_flora_relocation_bryophyte_position', 'flora_relocation', ['bryophyte_position'], unique=False)
    # ### end Alembic commands ###
