"""cambiado rescue_mammals

Revision ID: c62c050c6f7d
Revises: 16a2f6b10cb2
Create Date: 2023-11-25 02:06:30.136718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62c050c6f7d'
down_revision = '16a2f6b10cb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rescue_mammals', sa.Column('is_specie_confirmed', sa.Boolean(), nullable=False))
    op.add_column('rescue_mammals', sa.Column('genus_id', sa.Integer(), nullable=True))
    op.alter_column('rescue_mammals', 'specie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'rescue_mammals', 'genus', ['genus_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rescue_mammals', type_='foreignkey')
    op.alter_column('rescue_mammals', 'specie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('rescue_mammals', 'genus_id')
    op.drop_column('rescue_mammals', 'is_specie_confirmed')
    # ### end Alembic commands ###
