"""fix common name

Revision ID: e7b7fea1ea5b
Revises: a399d8bd219a
Create Date: 2023-07-26 16:41:35.552869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b7fea1ea5b'
down_revision = 'a399d8bd219a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_species_common_name', table_name='species')
    op.create_index(op.f('ix_species_common_name'), 'species', ['common_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_species_common_name'), table_name='species')
    op.create_index('ix_species_common_name', 'species', ['common_name'], unique=False)
    # ### end Alembic commands ###
