"""agregando rescue herpetofauna age group and gender

Revision ID: e878fcaf8e6a
Revises: 6cb97f52e0f7
Create Date: 2023-10-25 03:04:52.174046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e878fcaf8e6a'
down_revision = '6cb97f52e0f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mark_herpetofauna_age_group_id_fkey', 'mark_herpetofauna', type_='foreignkey')
    op.drop_column('mark_herpetofauna', 'age_group_id')
    op.drop_column('mark_herpetofauna', 'gender')
    op.add_column('rescue_herpetofauna', sa.Column('gender', sa.Boolean(), nullable=True))
    op.add_column('rescue_herpetofauna', sa.Column('age_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rescue_herpetofauna', 'age_group', ['age_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rescue_herpetofauna', type_='foreignkey')
    op.drop_column('rescue_herpetofauna', 'age_group_id')
    op.drop_column('rescue_herpetofauna', 'gender')
    op.add_column('mark_herpetofauna', sa.Column('gender', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('mark_herpetofauna', sa.Column('age_group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('mark_herpetofauna_age_group_id_fkey', 'mark_herpetofauna', 'age_group', ['age_group_id'], ['id'])
    # ### end Alembic commands ###
