"""corrgiendo nombre de columna atributo

Revision ID: eda70868f57f
Revises: fa086197fd27
Create Date: 2023-07-31 14:26:36.657073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda70868f57f'
down_revision = 'fa086197fd27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('atribute', sa.String(), nullable=True))
    op.drop_index('ix_images_atrrbute', table_name='images')
    op.create_index(op.f('ix_images_atribute'), 'images', ['atribute'], unique=False)
    op.drop_column('images', 'atrrbute')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('atrrbute', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_images_atribute'), table_name='images')
    op.create_index('ix_images_atrrbute', 'images', ['atrrbute'], unique=False)
    op.drop_column('images', 'atribute')
    # ### end Alembic commands ###
