"""nullable for columns rescue flora

Revision ID: f17b05f2937e
Revises: c6d7b221f5e3
Create Date: 2023-11-19 13:37:06.770137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17b05f2937e'
down_revision = 'c6d7b221f5e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flora_rescue', 'growth_habit',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('flora_rescue', 'epiphyte_phenology',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('flora_rescue', 'health_status_epiphyte',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('flora_rescue', 'microhabitat',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('flora_rescue', 'other_observations',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_flora_rescue_other_observations', table_name='flora_rescue')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_flora_rescue_other_observations', 'flora_rescue', ['other_observations'], unique=False)
    op.alter_column('flora_rescue', 'other_observations',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('flora_rescue', 'microhabitat',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('flora_rescue', 'health_status_epiphyte',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('flora_rescue', 'epiphyte_phenology',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('flora_rescue', 'growth_habit',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
