"""incluyendo atribucion fotos especies

Revision ID: fa086197fd27
Revises: b53563f05f17
Create Date: 2023-07-31 14:14:52.751057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa086197fd27'
down_revision = 'b53563f05f17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('atrrbute', sa.String(), nullable=True))
    op.create_index(op.f('ix_images_atrrbute'), 'images', ['atrrbute'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_atrrbute'), table_name='images')
    op.drop_column('images', 'atrrbute')
    # ### end Alembic commands ###
